### ISSUE TITLE
Cannot recreate the file tree

### ISSUE THREAD

**Issue by sathishzuss** [CalinaCristian/source-from-zeit-deployment#15]
![image](https://user-images.githubusercontent.com/88097120/196445030-c393ded0-5fba-4d91-a523-c04906085546.png)

**Comment by CalinaCristian** [comment]
Have you run this with the latest version? I don't seem to be getting errors while trying to recreate the structure 🤔 @StarkIndustriesTG 

What type of files do you have there? It shouldn't matter, it should work with any type though

**Comment by ghost** [comment]
its creating blank folder for me , i have deleted code from ggithub plz tell how to download

**Comment by bigmistqke** [comment]
+1 I get the same error

**Comment by issacting93** [comment]
Hi I have the same problem, any suggestions on how to fix it?

**Comment by yooosef3** [comment]
> ![image](https://user-images.githubusercontent.com/88097120/196445030-c393ded0-5fba-4d91-a523-c04906085546.png)

did you solve this error?

**Comment by uncledru** [comment]
~It looks like the `directory` object no longer has `children`~

```json
  { "type": "directory", "name": "404" },
  { "type": "directory", "name": "_nuxt" },
  { "type": "directory", "name": "account" },
  { "type": "directory", "name": "activity" },
  { "type": "directory", "name": "components" },
  { "type": "directory", "name": "favicon" },
  { "type": "directory", "name": "groups" },
  { "type": "directory", "name": "img" },
  { "type": "directory", "name": "landing" },
  { "type": "directory", "name": "oauth" },
  { "type": "directory", "name": "onboard" },
  { "type": "directory", "name": "sharepoint" },
  { "type": "directory", "name": "users" }
 ```
 
 🤔 
 
 The [FileTree](https://vercel.com/docs/rest-api#interfaces/file-tree) interface seems to have the property as optional.

**Comment by anjana784** [comment]
same error :(

**Comment by jonathanquaade** [comment]
Same error here :(

**Comment by narendrapanchal** [comment]
![image](https://github.com/CalinaCristian/source-from-vercel-deployment/assets/75387271/0d89e988-f03c-45d9-87ee-def87a30f103)
same error

**Comment by CalinaCristian** [comment]
fixed by @AliAryanTech [here](https://github.com/CalinaCristian/source-from-vercel-deployment/issues/20#issuecomment-1823566184)
