### ISSUE TITLE
canot recreate the file structure 

### ISSUE THREAD

**Issue by rajesh-adhikari** [CalinaCristian/source-from-zeit-deployment#20]
please look into it. i dont have source code.and i need it to summit so please help

**Comment by ilevennet** [comment]
Sme issue, personal account (hobby) on verse. No Team

**Comment by Kingbonwa1994** [comment]
i have reproduced the errror

**Comment by Kingbonwa1994** [comment]
> please look into it. i dont have source code.and i need it to summit so please help

did you resolve it

**Comment by ghost** [comment]
Same error here.

**Comment by TenTh0usand** [comment]
same error:
Cannot recreate the file tree. Please raise an issue here: https://github.com/CalinaCristian/source-from-vercel-deployment/issues !

**Comment by AliAryanTech** [comment]
I've tackled the file structure recreation problem and submitted a pull request. [Here](https://github.com/CalinaCristian/source-from-vercel-deployment/pull/21)

**Comment by CalinaCristian** [comment]
Thank you @AliAryanTech -- didn't get the chance to go over those issues ! Approved & Merged your PR.

**Comment by CalinaCristian** [comment]
published version [4.1.0](https://www.npmjs.com/package/source-from-vercel-deployment?activeTab=versions) with the fix.
